apiVersion: v1
kind: ServiceAccount
metadata:
  name: octops-controller
  labels:
    app: agones-event-broadcaster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octops-controller
  labels:
    app: agones-event-broadcaster
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["agones.dev"]
    resources: ["fleets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octops-controller
  labels:
    app: agones-event-broadcaster
subjects:
  - kind: User
    name: system:serviceaccount:default:octops-controller
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octops-controller
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: octops-image-syncer
  labels:
    name: octops-image-syncer
spec:
  selector:
    matchLabels:
      name: octops-image-syncer
  template:
    metadata:
      labels:
        name: octops-image-syncer
    spec:
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      serviceAccountName: octops-controller
      imagePullSecrets:
        - name: haabiz
      containers:
        - name: octops-image-syncer
          image: ghcr.io/haabiz-game/image-syncer:latest
          args:
            - "--sync-period=15s"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: CONN_TARGET
              value: "unix:///run/k3s/containerd/containerd.sock"
          volumeMounts:
            - name: runtime-sock
              mountPath: /run/k3s/containerd
              readOnly: false
          resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              cpu: 100m
              memory: 100Mi
      terminationGracePeriodSeconds: 30
      volumes:
        - name: runtime-sock
          hostPath:
            path: /run/k3s/containerd
            type: Directory
